# Generated by Django 6.1.1 on 2026-09-11 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.CharField(max_length=20)),
                ('order_type', models.CharField(choices=[('dinein', 'Dine-in'), ('takeaway', 'Takeaway')], default='dinein', max_length=10)),
                ('items', models.JSONField()),
                ('subtotal', models.PositiveIntegerField()),
                ('packing_charge', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('new', 'New'), ('preparing', 'Preparing'), ('completed', 'Completed')], default='new', max_length=12)),
                ('source', models.CharField(choices=[('customer', 'Customer (QR)'), ('staff', 'Staff Entry')], default='customer', max_length=10)),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-placed_at'],
            },
        ),
    ]
