// Real Raghuveer Cafe menu, transcribed from the printed menu boards.
// Where an item has Small/Big or Maida/Wheat pricing, `price` is the base
// (smaller/cheaper) option and the other size is noted in `desc`.
// Prices updated: +₹10 on all items except Cold Drinks & Mocktails.

export const CATEGORY_META = {
  "French Fries": { icon: "🍟", color: "#f5a623" },
  Maggi: { icon: "🍜", color: "#ef4444" },
  Burgers: { icon: "🍔", color: "#f97316" },
  Pasta: { icon: "🍝", color: "#ec4899" },
  Nuggets: { icon: "🍗", color: "#eab308" },
  Momos: { icon: "🥟", color: "#14b8a6" },
  Sandwiches: { icon: "🥪", color: "#84cc16" },
  "Frankie Rolls": { icon: "🌯", color: "#f59e0b" },
  Pizza: { icon: "🍕", color: "#ef4444" },
  "Hot Coffee": { icon: "☕", color: "#a16207" },
  "Cold Coffee": { icon: "🥤", color: "#8b5cf6" },
  Milkshakes: { icon: "🥛", color: "#ec4899" },
  "Cad-B Shakes": { icon: "🍫", color: "#92400e" },
  Mastani: { icon: "🍨", color: "#d946ef" },
  "Cold Drinks & Mocktails": { icon: "🍹", color: "#06b6d4" },
  Combos: { icon: "🍱", color: "#22c55e" },
};

export const MENU = [
  {
    category: "French Fries",
    items: [
      { id: "f1", name: "Salted French Fries", price: 70, desc: "Big ₹100" },
      { id: "f2", name: "Peri Peri Fries", price: 80, desc: "Big ₹110" },
      { id: "f3", name: "Masala French Fries", price: 100, desc: "Big ₹130" },
      { id: "f4", name: "Liquid Cheese Fries", price: 100, desc: "Big ₹130" },
      { id: "f5", name: "Double Cheese Fries", price: 110, desc: "Big ₹140" },
      { id: "f6", name: "Masala Peri Peri Fries", price: 110, desc: "Big ₹140" },
      { id: "f7", name: "Raghuveer Spl. Fries", price: 120, desc: "Big ₹150" },
      { id: "f8", name: "Liquid Cheese Masala Fries", price: 120, desc: "Big ₹150" },
      { id: "f9", name: "Double Cheese Masala Fries", price: 130, desc: "Big ₹160" },
      { id: "f10", name: "Raghuveer Spl. Masala Fries", price: 140, desc: "Big ₹170" },
    ],
  },
  {
    category: "Maggi",
    items: [
      { id: "mg1", name: "Regular Maggi", price: 80, desc: "" },
      { id: "mg2", name: "Masala Maggi", price: 100, desc: "" },
      { id: "mg3", name: "Vegetable Spl. Maggi", price: 100, desc: "" },
      { id: "mg4", name: "Cheese Maggi", price: 110, desc: "" },
      { id: "mg5", name: "Raghuveer Spl. Maggi", price: 120, desc: "" },
    ],
  },
  {
    category: "Burgers",
    items: [
      { id: "bu1", name: "Veg Aaloo Tikki Burger", price: 70, desc: "Wheat bun ₹80" },
      { id: "bu2", name: "Cheese Aaloo Tikki Burger", price: 80, desc: "Wheat bun ₹90" },
      { id: "bu3", name: "Veg. Burger", price: 80, desc: "Wheat bun ₹90" },
      { id: "bu4", name: "Chilli Potato Burger", price: 80, desc: "Wheat bun ₹90" },
      { id: "bu5", name: "Raghuveer Spl. Tikki Burger", price: 90, desc: "Wheat bun ₹100" },
      { id: "bu6", name: "Veg. Cheese Burger", price: 90, desc: "Wheat bun ₹100" },
      { id: "bu7", name: "Chilli Potato Cheese Burger", price: 90, desc: "Wheat bun ₹100" },
      { id: "bu8", name: "Raghuveer Spl. Burger", price: 100, desc: "Wheat bun ₹110" },
      { id: "bu9", name: "Raghuveer Spl. Chilli Burger", price: 100, desc: "Wheat bun ₹110" },
      { id: "bu10", name: "Veg Cheese Tandoor Burger", price: 110, desc: "Wheat bun ₹120" },
      { id: "bu11", name: "Raghuveer Spl. Tandoor Burger", price: 120, desc: "Wheat bun ₹130" },
      { id: "bu12", name: "Raghuveer Spl. Chilli Tandoor Burger", price: 120, desc: "Wheat bun ₹130" },
      { id: "bu13", name: "Paneer Cheese Burger", price: 150, desc: "Wheat bun ₹160" },
      { id: "bu14", name: "Raghuveer Spl. Paneer Burger", price: 160, desc: "Wheat bun ₹170" },
      { id: "bu15", name: "Raghuveer Paneer Tandoor Burger", price: 170, desc: "Wheat bun ₹180" },
    ],
  },
  {
    category: "Pasta",
    items: [
      { id: "p1", name: "White Pasta", price: 130, desc: "" },
      { id: "p2", name: "Red Pasta", price: 140, desc: "" },
      { id: "p3", name: "White Cheese Pasta", price: 150, desc: "" },
      { id: "p4", name: "Red Cheese Pasta", price: 160, desc: "" },
    ],
  },
  {
    category: "Nuggets",
    items: [
      { id: "n1", name: "Veggie Fingers", price: 90, desc: "" },
      { id: "n2", name: "Chilli-Garlic Bites", price: 90, desc: "" },
      { id: "n3", name: "Cheese Corn Triangles", price: 110, desc: "" },
    ],
  },
  {
    category: "Momos",
    items: [
      { id: "mo1", name: "Mix Veg. Momos", price: 110, desc: "Steamed or fried" },
      { id: "mo2", name: "Paneer Momos", price: 120, desc: "Steamed or fried" },
      { id: "mo3", name: "Cheese Corn Momos", price: 130, desc: "Steamed or fried" },
      { id: "mo4", name: "Raghuveer Spl. Momos", price: 150, desc: "Steamed or fried" },
    ],
  },
  {
    category: "Sandwiches",
    items: [
      { id: "sw1", name: "Veg Sandwich", price: 60, desc: "Wheat bread ₹70" },
      { id: "sw2", name: "Veg Cheese Sandwich", price: 70, desc: "Wheat bread ₹80" },
      { id: "sw3", name: "Veg Cheese Grill Sandwich", price: 80, desc: "Wheat bread ₹90" },
      { id: "sw4", name: "Chocolate Sandwich", price: 80, desc: "Wheat bread ₹90" },
      { id: "sw5", name: "Sweet Corn Cheese Grill Sandwich", price: 90, desc: "Wheat bread ₹100" },
      { id: "sw6", name: "Paneer Cheese Grill Sandwich", price: 100, desc: "Wheat bread ₹110" },
      { id: "sw7", name: "Raghuveer Spl. Cheese Grill Sandwich", price: 110, desc: "Wheat bread ₹120" },
    ],
  },
  {
    category: "Frankie Rolls",
    items: [
      { id: "fr1", name: "Veg. Frankie Roll", price: 110, desc: "" },
      { id: "fr2", name: "Veg. Cheese Frankie Roll", price: 130, desc: "" },
      { id: "fr3", name: "Paneer Frankie Roll", price: 130, desc: "" },
      { id: "fr4", name: "Veg. Cheese Tandoor Frankie Roll", price: 140, desc: "" },
      { id: "fr5", name: "Paneer Cheese Frankie Roll", price: 140, desc: "" },
      { id: "fr6", name: "Raghuveer Spl. Tandoor Frankie Roll", price: 150, desc: "" },
      { id: "fr7", name: "Raghuveer Spl. Paneer Frankie Roll", price: 160, desc: "" },
    ],
  },
  {
    category: "Pizza",
    items: [
      { id: "pz1", name: "Veg. Cheese Pizza", price: 140, desc: "6\" · Med ₹160 · Big ₹260" },
      { id: "pz2", name: "Jain Veg. Cheese Pizza", price: 140, desc: "6\" · Med ₹170 · Big ₹270" },
      { id: "pz3", name: "Margherita Pizza", price: 150, desc: "6\" · Med ₹170 · Big ₹270" },
      { id: "pz4", name: "Sweet Corn + Veg. Cheese Pizza", price: 150, desc: "6\" · Med ₹170 · Big ₹270" },
      { id: "pz5", name: "Baby Corn + Veg. Cheese Pizza", price: 150, desc: "6\" · Med ₹170 · Big ₹270" },
      { id: "pz6", name: "Chocolate Cheese Pizza", price: 150, desc: "6\" · Med ₹170 · Big ₹270" },
      { id: "pz7", name: "Mushroom + Veg. + Corn Cheese Pizza", price: 160, desc: "6\" · Med ₹180 · Big ₹280" },
      { id: "pz8", name: "Paneer Yummy Cheese Pizza", price: 170, desc: "6\" · Med ₹190 · Big ₹290" },
      { id: "pz9", name: "Mix Loaded Cheese Pizza", price: 170, desc: "6\" · Med ₹200 · Big ₹300" },
      { id: "pz10", name: "Farm House Pizza", price: 190, desc: "6\" · Med ₹210 · Big ₹310" },
      { id: "pz11", name: "Jain Cheese Burst Pizza", price: 190, desc: "6\" · Med ₹220 · Big ₹320" },
      { id: "pz12", name: "Yummy Cheese Burst Pizza", price: 190, desc: "6\" · Med ₹220 · Big ₹320" },
      { id: "pz13", name: "Italian Yummy Cheese Burst Pizza", price: 190, desc: "6\" · Med ₹220 · Big ₹320" },
      { id: "pz14", name: "Raghuveer Spl. Tandoor Burst Pizza", price: 220, desc: "6\" · Med ₹250 · Big ₹350" },
      { id: "pz15", name: "Raghuveer Special Paneer Pizza", price: 220, desc: "6\" · Med ₹250 · Big ₹350" },
      { id: "pz16", name: "Volcano Cheese Pizza", price: 230, desc: "6\" · Med ₹260 · Big ₹360" },
      { id: "pz17", name: "Dryfruit Raghuveer Spl. Cheese Pizza", price: 230, desc: "6\" · Med ₹260 · Big ₹360" },
      { id: "pz18", name: "Raghuveer Cheese Burst Punjabi Tadka", price: 240, desc: "6\" · Med ₹270 · Big ₹370" },
    ],
  },
  {
    category: "Hot Coffee",
    items: [
      { id: "hc1", name: "Regular Hot Coffee", price: 40, desc: "" },
      { id: "hc2", name: "Chocolate Hot Coffee", price: 50, desc: "" },
      { id: "hc3", name: "Couple Hot Coffee", price: 60, desc: "Serves 2" },
      { id: "hc4", name: "Couple Chocolate Hot Coffee", price: 70, desc: "Serves 2" },
    ],
  },
  {
    category: "Cold Coffee",
    items: [
      { id: "cc1", name: "Regular Cold Coffee", price: 60, desc: "Jumbo glass ₹80" },
      { id: "cc2", name: "Chocolate Cold Coffee", price: 70, desc: "Jumbo glass ₹90" },
      { id: "cc3", name: "Chocolate CF + Ice-Cream", price: 80, desc: "Jumbo glass ₹100" },
      { id: "cc4", name: "Chocolate CF + Chocochips/Crush", price: 90, desc: "Jumbo glass ₹110" },
      { id: "cc5", name: "Chocolate CF + Chocochips/Crush + Ice-Cream", price: 110, desc: "Jumbo glass ₹130" },
    ],
  },
  {
    category: "Milkshakes",
    items: [
      { id: "ms1", name: "Vanilla Milkshake", price: 90, desc: "+ Ice-Cream ₹110" },
      { id: "ms2", name: "Mango Milkshake", price: 90, desc: "+ Ice-Cream ₹110" },
      { id: "ms3", name: "Sweet Strawberry Milkshake", price: 90, desc: "+ Ice-Cream ₹110" },
      { id: "ms4", name: "Crunchy Oreo Milkshake", price: 90, desc: "+ Ice-Cream ₹110" },
      { id: "ms5", name: "Apple + Butterscotch Milkshake", price: 80, desc: "" },
      { id: "ms6", name: "Apple + Ice-Cream Milkshake", price: 90, desc: "" },
      { id: "ms7", name: "KitKat Milkshake", price: 100, desc: "+ Ice-Cream ₹110" },
      { id: "ms8", name: "KitKat + Oreo Milkshake", price: 100, desc: "" },
      { id: "ms9", name: "Raghuveer Spl. Mix Milkshake", price: 130, desc: "" },
    ],
  },
  {
    category: "Cad-B Shakes",
    items: [
      { id: "cb1", name: "Vanilla Cad-B", price: 110, desc: "" },
      { id: "cb2", name: "Chocolate Cad-B", price: 110, desc: "" },
      { id: "cb3", name: "Raghuveer Spl. Mix Cad-B", price: 120, desc: "" },
      { id: "cb4", name: "Mango Spl. Cad-B", price: 120, desc: "" },
      { id: "cb5", name: "Jumbo Chocolate Cad-B", price: 130, desc: "" },
    ],
  },
  {
    category: "Mastani",
    items: [
      { id: "ma1", name: "Mango Dryfruit Mastani", price: 120, desc: "" },
      { id: "ma2", name: "Butterscotch Dryfruit Mastani", price: 120, desc: "" },
      { id: "ma3", name: "Strawberry Dryfruit Mastani", price: 120, desc: "" },
      { id: "ma4", name: "Peshwai Mastani", price: 120, desc: "" },
      { id: "ma5", name: "Raghuveer Spl. Mastani", price: 140, desc: "" },
    ],
  },
  {
    category: "Cold Drinks & Mocktails",
    items: [
      { id: "cd1", name: "Coca-Cola", price: 50, desc: "" },
      { id: "cd2", name: "Sprite", price: 50, desc: "" },
      { id: "cd3", name: "Thums Up", price: 50, desc: "" },
      { id: "cd4", name: "Ice-Cream Soda", price: 50, desc: "" },
      { id: "mk1", name: "Watermelon Mocktail", price: 80, desc: "" },
      { id: "mk2", name: "Lemon Grass + Ginger Mocktail", price: 80, desc: "" },
      { id: "mk3", name: "Green Apple Mocktail", price: 80, desc: "" },
      { id: "mk4", name: "Blueberry Mocktail", price: 90, desc: "" },
      { id: "mk5", name: "Mogita Mint Mocktail", price: 90, desc: "" },
      { id: "mk6", name: "Pina Colada Mocktail", price: 90, desc: "" },
    ],
  },
  {
    category: "Combos",
    items: [
      { id: "co1", name: "Mini Combo A", price: 209, desc: "Veg Cheese Burger + Salted Fries + Chocolate Cold Coffee (was ₹240)" },
      { id: "co2", name: "Regular Combo", price: 179, desc: "Veg Sandwich + Peri-Peri Fries + Cold Coffee (was ₹210)" },
      { id: "co3", name: "Special Combo A", price: 259, desc: "Raghuveer Spl. Burger + Spl. Fries + Coke/Cold Coffee (was ₹320)" },
      { id: "co4", name: "Mini Combo", price: 239, desc: "Veg Cheese Frankie Roll + Peri Peri Fries + Cold Coffee/Coke (was ₹280)" },
      { id: "co5", name: "Regular Combo A", price: 279, desc: "Sweet Corn + Veg Cheese Pizza (M) + Peri-Peri Fries + Coke/Cold Coffee (was ₹320)" },
      { id: "co6", name: "Regular Combo B", price: 229, desc: "White Pasta + Salted Fries + Coke/Cold Coffee (was ₹279)" },
      { id: "co7", name: "Nuggets Fries Combo", price: 229, desc: "Cheese Corn Triangles + Peri-Peri Fries + Cold Coffee/Coke (was ₹260)" },
      { id: "co8", name: "Special Combo", price: 249, desc: "Raghuveer Spl. Grill Sandwich + Spl. Fries + Chocolate Cold Coffee (was ₹370)" },
      { id: "co9", name: "Mini Combo B", price: 309, desc: "Spl. Burst Pizza (S) + Peri-Peri Fries + Cold Coffee/Coke (was ₹370)" },
      { id: "co10", name: "Special Combo B", price: 409, desc: "Spl. Burst Pizza (M) + Peri-Peri Fries + Cold Coffee (was ₹460)" },
    ],
  },
];